# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_screening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('ord', models.SmallIntegerField(default=50, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Жанр',
                'ordering': ['ord'],
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
        migrations.AddField(
            model_name='show',
            name='genre',
            field=models.ManyToManyField(blank=True, to='movie.Genre', verbose_name='Жанры'),
        ),
    ]
