# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20151206_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='genre',
            new_name='genre_list',
        ),
    ]
