# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20151206_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='on_archive',
            field=models.BooleanField(default=False, verbose_name='Показывать как архивный'),
        ),
        migrations.AddField(
            model_name='show',
            name='short_desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткое описание'),
        ),
    ]
