# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20151206_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='on_catalog',
            field=models.BooleanField(default=False, verbose_name='Показывать в каталоге'),
        ),
    ]
