# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_show_on_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['ord', 'title'], 'verbose_name': 'Релиз', 'verbose_name_plural': 'Релизы'},
        ),
        migrations.RemoveField(
            model_name='show',
            name='short_desc',
        ),
        migrations.AlterField(
            model_name='show',
            name='original_title',
            field=models.CharField(help_text='Пример Mission: Impossible — Rogue Nation', max_length=255, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='show',
            name='trailer',
            field=models.TextField(help_text='Пример Li7bv9lbaBo', verbose_name='Ссылка на видео трейлера'),
        ),
    ]
