# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0008_auto_20151029_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='slug',
            field=models.URLField(default='0', unique=True, verbose_name='название в url'),
        ),
    ]
